### ISSUE TITLE
Doesn't work with React Native 0.46.4

### ISSUE THREAD

**Issue by itchingpixels** [mockingbot/react-native-zip-archive#59]
`:react-native-zip-archive:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/mark/Dev/drops-react-native/node_modules/react-native-zip-archive/android/src/main/java/com/rnziparchive/RNZipArchivePackage.java:11: error: RNZipArchivePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNZipArchivePackage implements ReactPackage {
       ^
1 error
:react-native-zip-archive:compileReleaseJavaWithJavac FAILED`

The library compiled fine with RN 0.45.1

Related issue:
https://github.com/react-native-community/react-native-svg/issues/412

**Comment by plrthink** [comment]
It's wired I think since the RNZipArchivePackage class did implement the `createJSModules` method. Which version of the package you're using?

**Comment by itchingpixels** [comment]
@plrthink : ahh, I'm sorry. I haven't been using the latest version. will close this, sorry again! I saw that a few days ago createJSModules() has been moved back.

**Comment by plrthink** [comment]
@itchingpixels  it's ok ;)

Yeah, since it's not necessary after rn@0.47+. But we added it back in current master branch and still trying to not deliver a break change release. But this is just in the development stage and not published yet. So if you install the latest version via npm, everything should just work.

**Comment by itchingpixels** [comment]
unfortunately we're relying another fix that have been merged to master
(podspec). so we can not use the latest release, but need to depend on a
specific commit.

**Comment by plrthink** [comment]
ok, I think latest commit on the master branch would work fine, and once we finish this issue https://github.com/mockingbot/react-native-zip-archive/issues/57 we would release a new version.
